# This file was generated by GoReleaser. DO NOT EDIT.
cask "firestore" do
  version "1.8.5"

  on_macos do
    on_intel do
      sha256 "1ba71ec0a8667439044952f5d41ad257d44ce90604dd54f49f6e1c05125b73de"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c48634c06684520425ed2f398966b7056a05c8f80d78c2eedfb31f7c00a17f0"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2796f97bde47a39379bf90a8ddfc1a2a1492ecd369222c0ab6e12eacfa355f89"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "765d0add2c7ecd76e0a2ec8945fb78cb0531481535f7369fc938dc9a08a24357"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_arm64.tar.gz"
    end
  end

  name "firestore"
  desc "Command line utility to facilitate operations with Firestore"
  homepage "https://github.com/gugahoi/firestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firestore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firestore"]
    end
  end

  # No zap stanza required

end
