# This file was generated by GoReleaser. DO NOT EDIT.
cask "firestore" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "37709b3b50e9ee89e4b1bceb15e0b41fcfc9545d0f9c1c215e652411259570a8"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "62818be3af2165fdb68761f919b584869e37458791783a4990c274f093fdb204"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f36aa20392c6a38213002913675ed4d6482292bb408edab8118cb1e9d154b21"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b816646a58dd60a6d320d8c806811cddf83346f3af06b3e8fff9272b06bc43dc"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_arm64.tar.gz"
    end
  end

  name "firestore"
  desc "Command line utility to facilitate operations with Firestore"
  homepage "https://github.com/gugahoi/firestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firestore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firestore"]
    end
  end

  # No zap stanza required

end
