# This file was generated by GoReleaser. DO NOT EDIT.
cask "firestore" do
  version "1.8.4"

  on_macos do
    on_intel do
      sha256 "e4e029419915a6cf47db561e83bb5171b3ecae2b907802bc20bb217b876e2f05"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cbfed85d33e0626a021257657a0a94eabfa8cf5d335aa2df529337f8ee283d1d"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d62d5ae48d288df577741f97e625f2d9d560f50332b8dcfdffe0fbc013c47eb"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aa337880c7f4bb5a6ee990524641b4915f5f209545aa0467f7116da9764a86c7"
      url "https://github.com/gugahoi/firestore/releases/download/v#{version}/firestore_Linux_arm64.tar.gz"
    end
  end

  name "firestore"
  desc "Command line utility to facilitate operations with Firestore"
  homepage "https://github.com/gugahoi/firestore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firestore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firestore"]
    end
  end

  # No zap stanza required

end
